force-app/main/default/objects/Contact/fields/External_System_Id__c.field-meta.xml
<CustomField>
    <fullName>External_System_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External System Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Customer home country</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Product should match with customer home country</errorMessage>
        <filterItems>
            <field>Product__c.Country__c</field>
            <operation>equals</operation>
            <valueField>$Source.Home_Country__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Card Replacement Cost fee</description>
    <inlineHelpText>Cost to customer on replacement of card</inlineHelpText>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer_ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>Customer_ATM_Fee__c</fullName>
    <formula>IF((ATM_Fee__c=0),&apos;Free&apos;, TEXT(ATM_Fee__c *100)+&apos;%&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>ATM Fee cost to the customer</inlineHelpText>
    <label>Customer ATM Fee</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer_cost_per_calendar_month__c.field-meta.xml
<CustomField>
    <fullName>Customer_cost_per_calendar_month__c</fullName>
    <formula>IF( ISBLANK(Cost_per_Calendar_Month__c),&apos;N/a&apos;, TEXT(Cost_per_Calendar_Month__c))</formula>
    <inlineHelpText>Monthly Fee to the customer</inlineHelpText>
    <label>Customer cost per calendar month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Account Type</description>
    <inlineHelpText>Type of account</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <description>Type of Account</description>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerDetailServicesTest.cls
@isTest
public class CustomerDetailServicesTest {
    @TestSetup
    static void generateData(){
        Product__c p = TestDataFactory.getTestProduct('Standard','EUR','DE',1.7,6,0);
        Contact con = TestDataFactory.getTestContactWithProduct('Test','Contact','EUR','DE',p.Id,'123');
    }

    @isTest
    static void testValidCustomerDetails(){
        Contact c = [SELECT Id, LastName, FirstName,Product__c, Product__r.Name, Product__r.type__c,Product__r.Customer_ATM_Fee__c ,Product__r.Customer_cost_per_calendar_month__c,Product__r.CurrencyIsoCode,Product__r.Card_Replacement_Cost__c, Home_Country__c FROM Contact WHERE External_System_Id__c='123'];
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/customer/123'; 
        req.httpMethod = 'Get';
        RestContext.request = req;
        RestContext.response = res; 
        Test.startTest();
        CustomerDetailServices.CustomerWrapper cwrapper = CustomerDetailServices.doGet();
        system.assertEquals(cwrapper.isSuccess, true );
        system.assertEquals(cwrapper.firstName, c.FirstName);
        system.assertEquals(cwrapper.lastName, c.LastName );
        system.assertEquals(cwrapper.country, c.Home_Country__c );
        system.assertEquals(cwrapper.accountMonthlyCost, c.Product__r.Customer_cost_per_calendar_month__c);
        system.assertEquals(cwrapper.atmFee, c.Product__r.Customer_ATM_Fee__c );
        system.assertEquals(cwrapper.accountType, c.Product__r.type__c );
        system.assertEquals(cwrapper.replacementCost,c.Product__r.Card_Replacement_Cost__c );
        system.assertEquals(cwrapper.currencyType, c.Product__r.CurrencyIsoCode );
        Test.stopTest();  
    }

    @isTest
    static void testInvalidCustomerDetails(){
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/customer/invalid'; 
        req.httpMethod = 'Get';
        RestContext.request = req;
        RestContext.response = res; 
        Test.startTest();
        CustomerDetailServices.CustomerWrapper cwrapper = CustomerDetailServices.doGet();
        system.assertEquals(cwrapper.isSuccess, false );
        system.assertEquals(String.isBlank(cwrapper.errorMessage),true );
        Test.stopTest();  
    }

    @isTest
    static void testValidCustomerWithNoProductDetails(){
        Contact  c = [SELECT id,Product__c FROM Contact];
        c.Product__c = null;
        update c;
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/customer/123'; 
        req.httpMethod = 'Get';
        RestContext.request = req;
        RestContext.response = res; 
        Test.startTest();
        CustomerDetailServices.CustomerWrapper cwrapper = CustomerDetailServices.doGet();
        system.assertEquals(cwrapper.isSuccess, true );
        system.assertEquals(String.isBlank(cwrapper.errorMessage),false );
        Test.stopTest();  
    }
}