force-app/main/default/objects/Contact/fields/External_System_Id__c.field-meta.xml
<CustomField>
    <fullName>External_System_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External System Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Customer home country</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Product should match with customer home country</errorMessage>
        <filterItems>
            <field>Product__c.Country__c</field>
            <operation>equals</operation>
            <valueField>$Source.Home_Country__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee__c</fullName>
    <description>ATM fee on different account types</description>
    <inlineHelpText>ATM maintenance fee</inlineHelpText>
    <label>ATM Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Card Replacement Cost fee</description>
    <inlineHelpText>Cost to customer on replacement of card</inlineHelpText>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <description>Monthly cost of account</description>
    <inlineHelpText>Monthly maintenance cost to customer</inlineHelpText>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <inlineHelpText>Product belongs to which country</inlineHelpText>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Account Type</description>
    <inlineHelpText>Type of account</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <description>Type of Account</description>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {

    //Insert default test contact
    public static Contact getTestContact(){
        Contact c = new Contact();
        c.FirstName = 'Test';
        c.LastName = 'Contact';
        c.currencyISOcode='EUR';
        insert c;
        return c;
    }
    //Insert test contact with specific details
    public static Contact getTestContactWithProduct(String firstName, String lastName, String currencyCode,String homeCountry, Id productId, String extId){
        Contact c = new Contact();
        c.FirstName = firstName;
        c.LastName = lastName;
        //populate default currencty if no currency passed to parameter
        c.currencyISOcode = String.isBlank(currencyCode) ? 'EUR' : currencyCode;
        c.Home_Country__c =  homeCountry;
        c.Product__c = productId;
        c.External_System_Id__c =  extId;
        insert c;
        return c;
    }

    //Generate product
    public static Product__c getTestProduct(String type, String currencyCode, String country, Decimal atmFee, Decimal cardReplaceCost, Decimal monthlyFee){
        Product__c p = new Product__c();
        p.Type__c = type;
        //populate default currencty if no currency passed to parameter
        p.CurrencyIsoCode = String.isBlank(currencyCode) ? 'EUR' : currencyCode;
        p.Country__c = country;
        p.ATM_Fee__c = atmFee;
        p.Card_Replacement_Cost__c = cardReplaceCost;
        p.Cost_per_Calendar_Month__c =  monthlyFee;
        insert p;
        return p;
    }

    //Generate Case
    public static Case getCase(Contact customer,String currencyCode){
        Case c = new Case();
        c.ContactID = customer.Id;
        //populate default currencty if no currency passed to parameter
        c.CurrencyISOcode = String.isBlank(currencyCode) ? 'EUR' : currencyCode;
        c.Origin = 'Web';
        insert c;
        return c;
    }
}