force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Customer home country</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Product should match with customer home country</errorMessage>
        <filterItems>
            <field>Product__c.Country__c</field>
            <operation>equals</operation>
            <valueField>$Source.Home_Country__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Card Replacement Cost fee</description>
    <inlineHelpText>Cost to customer on replacement of card</inlineHelpText>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer_ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>Customer_ATM_Fee__c</fullName>
    <formula>IF((ATM_Fee__c=0),&apos;Free&apos;, TEXT(ATM_Fee__c *100)+&apos;%&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>ATM Fee cost to the customer</inlineHelpText>
    <label>Customer ATM Fee</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer_cost_per_calendar_month__c.field-meta.xml
<CustomField>
    <fullName>Customer_cost_per_calendar_month__c</fullName>
    <formula>IF( ISBLANK(Cost_per_Calendar_Month__c),&apos;N/a&apos;, TEXT(Cost_per_Calendar_Month__c))</formula>
    <inlineHelpText>Monthly Fee to the customer</inlineHelpText>
    <label>Customer cost per calendar month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Account Type</description>
    <inlineHelpText>Type of account</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <description>Type of Account</description>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerDetailServices.cls
@RestResource(urlMapping='/customer/*')
global with sharing class CustomerDetailServices {
    @HttpGet
    global static CustomerWrapper doGet() {
        CustomerWrapper cwrap = new CustomerWrapper();
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String customerUid = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        try {
            if(Utility.isValidSalesforceId(customerUid,Contact.class)){
                Contact cDetails = [SELECT Id, LastName, FirstName, Product__r.Name, Product__r.type__c,Product__r.Customer_ATM_Fee__c ,Product__r.Customer_cost_per_calendar_month__c,Product__r.CurrencyIsoCode,Product__r.Card_Replacement_Cost__c, Home_Country__c FROM Contact WHERE id=:customerUid ];
                cwrap.isSuccess = true;
                cwrap.firstName = cDetails.FirstName;
                cwrap.lastName = cDetails.LastName;
                cwrap.replacementCost = cDetails.Product__r.Card_Replacement_Cost__c;
                cwrap.accountMonthlyCost= cDetails.Product__r.Customer_cost_per_calendar_month__c;
                cwrap.accountType = cDetails.Product__r.type__c;
                cwrap.atmFee  = cDetails.Product__r.Customer_ATM_Fee__c;
                cwrap.country  = cDetails.Home_Country__c;
                cwrap.currencyType  = cDetails.Product__r.CurrencyIsoCode;
                
            }else{
                cwrap.isSuccess =false;
                cwrap.errorMessage = 'Invalid customer id';
            }
        } catch (Exception ex) {
            cwrap.isSuccess =false;
            cwrap.errorMessage = ex.getMessage();
        }
        return cwrap;
    }

    global class CustomerWrapper{
        public Boolean isSuccess {get;set;}
        public String errorMessage {get;set;}
        public String firstName {get;set;}
        public String lastName {get;set;}
        public String country {get;set;}
        public String accountMonthlyCost {get;set;}
        public String atmFee {get;set;}
        public String accountType {get;set;}
        public Decimal replacementCost {get;set;}
        public String currencyType {get;set;}
    }
}